#!/usr/bin/env python3
"""Generate a markdown daily study plan from the question bank.

Reads ``docs/questions.json`` (rebuild via ``tools/build_index.py``) and picks
a balanced mix of questions across categories, then renders a checklist-style
markdown plan with time budgets, links back to the source, and a self-eval
section that points at the system-design rubric where relevant.

Examples:
    # Today's default plan (3 algo + 1 system design + 1 behavioral)
    python tools/daily_plan.py

    # Focus on Amazon for a week, write to file
    python tools/daily_plan.py --company amazon --count 6 \
        --output ~/amazon-day1.md

    # Chinese output, custom mix
    python tools/daily_plan.py --lang zh \
        --mix algorithm:4,system-design:2

    # Reproducible plan for a known date
    python tools/daily_plan.py --date 2026-06-10
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import random
import sys
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX = REPO_ROOT / "docs" / "questions.json"
REVIEW_STATE = Path.home() / ".awesome-interview-streak.json"

DEFAULT_MIX = "algorithm:3,system-design:1,behavioral:1"

KIND_TIME_BUDGET_MIN = {
    "algorithm": 25,
    "system-design": 45,
    "behavioral": 10,
    "knowledge": 15,
    "other": 20,
}

TEMPLATES = {
    "en": {
        "title": "# Daily Prep Plan — {date}",
        "intro": (
            "Generated by `tools/daily_plan.py`. Total budget: **{total_min} min**. "
            "Tick each box as you finish; jot a one-line takeaway under each question."
        ),
        "section_questions": "## Questions",
        "section_eval": "## Self-evaluation",
        "section_notes": "## Notes",
        "section_extras": "## Stretch (if you finish early)",
        "q_heading": "### {idx}. {title}",
        "q_meta": "**Kind:** {kind}  |  **Difficulty:** {difficulty}  |  **Budget:** {budget} min  |  **Source:** [{file}:{line}]({file}#L{line})",
        "q_topics": "**Topics:** {topics}",
        "q_box": "- [ ] Read the prompt and restate it in your own words.",
        "q_box_algo": [
            "- [ ] Brute force first, state its time/space.",
            "- [ ] Optimize; explain the insight that unlocked the better bound.",
            "- [ ] Code it cleanly (Python or your interview language).",
            "- [ ] Walk through with a tricky test case (empty / single / overflow).",
            "- [ ] Note the **Common Pitfalls** the question lists \u2014 did you hit any?",
        ],
        "q_box_sd": [
            "- [ ] Clarify functional + non-functional requirements before drawing.",
            "- [ ] Back-of-envelope: QPS (read/write), storage, bandwidth, peak vs avg.",
            "- [ ] Sketch a clean high-level architecture (read path \u2260 write path).",
            "- [ ] Pick data model + storage with justification + sharding key.",
            "- [ ] One deep dive (algorithm or protocol level).",
            "- [ ] Name the consistency model + one failure scenario.",
            "- [ ] Score yourself against [system-design-rubric.md](mock-interviews/system-design-rubric.md).",
        ],
        "q_box_beh": [
            "- [ ] STAR structure: 1 sentence S, 1 T, 3-4 A, 1-2 R.",
            "- [ ] Quantify the result. No number = weak story.",
            "- [ ] Prep one follow-up: \"what would you do differently?\"",
        ],
        "q_takeaway": "**One-line takeaway:** _(fill in)_",
        "eval_items": [
            "- [ ] Did I hit my time budget on each question, or did I rabbit-hole?",
            "- [ ] Which question was weakest? Pick that topic for tomorrow.",
            "- [ ] Mark today done: `python tools/streak.py done`.",
        ],
        "no_picks_msg": "_No questions matched the filters._",
        "extras_intro": "Bonus picks across the same filters \u2014 attempt only if budget allows.",
        "mix_label": "Mix",
        "filters_label": "Filters",
    },
    "zh": {
        "title": "# \u6bcf\u65e5\u5907\u9762\u8ba1\u5212 \u2014 {date}",
        "intro": (
            "\u7531 `tools/daily_plan.py` \u751f\u6210\u3002\u603b\u9884\u7b97\uff1a**{total_min} \u5206\u949f**\u3002"
            "\u6bcf\u9898\u5b8c\u6210\u540e\u52fe\u4e0a\uff1b\u5728\u6bcf\u9898\u4e0b\u9762\u8bb0\u4e00\u53e5\u6536\u83b7\u3002"
        ),
        "section_questions": "## \u9898\u76ee",
        "section_eval": "## \u81ea\u6211\u590d\u76d8",
        "section_notes": "## \u7b14\u8bb0",
        "section_extras": "## \u62d3\u5c55\uff08\u63d0\u524d\u505a\u5b8c\u624d\u770b\uff09",
        "q_heading": "### {idx}. {title}",
        "q_meta": "**\u7c7b\u522b\uff1a**{kind}  |  **\u96be\u5ea6\uff1a**{difficulty}  |  **\u9884\u7b97\uff1a**{budget} \u5206\u949f  |  **\u51fa\u5904\uff1a**[{file}:{line}]({file}#L{line})",
        "q_topics": "**\u4e3b\u9898\uff1a**{topics}",
        "q_box": "- [ ] \u8bfb\u9898\uff0c\u7528\u81ea\u5df1\u7684\u8bdd\u590d\u8ff0\u4e00\u904d\u3002",
        "q_box_algo": [
            "- [ ] \u5148\u51fa\u66b4\u529b\u89e3\uff0c\u8bf4\u660e\u5176\u65f6\u95f4/\u7a7a\u95f4\u3002",
            "- [ ] \u4f18\u5316\uff1b\u8bf4\u51fa\u4ee4\u590d\u6742\u5ea6\u4e0b\u964d\u7684\u5173\u952e\u6d1e\u5bdf\u3002",
            "- [ ] \u5e72\u51c0\u5730\u5199\u51fa\u4ee3\u7801\uff08Python \u6216\u9762\u8bd5\u7528\u8bed\u8a00\uff09\u3002",
            "- [ ] \u7528\u4e00\u4e2a\u68d8\u624b\u6837\u4f8b\uff08\u7a7a/\u5355\u5143\u7d20/\u6ea2\u51fa\uff09\u8d70\u9a8c\u3002",
            "- [ ] \u770b\u9898\u76ee\u91cc\u7684 **\u5e38\u89c1\u5751**\uff0c\u4eca\u5929\u8e29\u4e2d\u4e86\u54ea\u51e0\u4e2a\uff1f",
        ],
        "q_box_sd": [
            "- [ ] \u52a8\u624b\u753b\u524d\u5148\u6f84\u6e05\u529f\u80fd + \u975e\u529f\u80fd\u9700\u6c42\u3002",
            "- [ ] \u8eab\u624b\u4f30\u7b97\uff1aQPS\uff08\u8bfb/\u5199\uff09\u3001\u5b58\u50a8\u3001\u5e26\u5bbd\u3001\u5cf0\u503c vs \u5e73\u5747\u3002",
            "- [ ] \u753b\u51fa\u5e72\u51c0\u9ad8\u5c42\u67b6\u6784\uff08\u8bfb\u8def\u5f84 \u2260 \u5199\u8def\u5f84\uff09\u3002",
            "- [ ] \u9009\u5b9a\u6570\u636e\u6a21\u578b + \u5b58\u50a8 + \u5206\u7247\u952e\uff0c\u7ed9\u51fa\u7406\u7531\u3002",
            "- [ ] \u4e00\u6b21 deep dive\uff08\u7b97\u6cd5\u6216\u534f\u8bae\u7ea7\uff09\u3002",
            "- [ ] \u70b9\u540d\u4e00\u81f4\u6027\u6a21\u578b + \u4e00\u4e2a\u5931\u8d25\u573a\u666f\u3002",
            "- [ ] \u5bf9\u7167 [system-design-rubric.zh.md](mock-interviews/system-design-rubric.zh.md) \u7ed9\u81ea\u5df1\u6253\u5206\u3002",
        ],
        "q_box_beh": [
            "- [ ] STAR \u7ed3\u6784\uff1a1 \u53e5 S\u30011 \u53e5 T\u30013-4 \u53e5 A\u30011-2 \u53e5 R\u3002",
            "- [ ] \u91cf\u5316\u7ed3\u679c\uff1b\u6ca1\u6709\u6570\u5b57 = \u6545\u4e8b\u4e0d\u591f\u786c\u3002",
            "- [ ] \u9884\u5907\u4e00\u6761\u8ffd\u95ee\uff1a\u201c\u91cd\u6765\u4f1a\u600e\u4e48\u505a\u5f97\u4e0d\u540c\uff1f\u201d",
        ],
        "q_takeaway": "**\u4e00\u53e5\u8bdd\u6536\u83b7\uff1a** _\uff08\u586b\u5199\uff09_",
        "eval_items": [
            "- [ ] \u6bcf\u9898\u90fd\u63a7\u5728\u9884\u7b97\u5185\u4e86\u5417\uff1f\u8fd8\u662f\u6389\u5751\u4e86\uff1f",
            "- [ ] \u54ea\u9898\u6700\u5dee\uff1f\u660e\u5929\u91cd\u70b9\u7ec3\u8be5\u4e3b\u9898\u3002",
            "- [ ] \u6253\u5361\uff1a`python tools/streak.py done`\u3002",
        ],
        "no_picks_msg": "_\u6ca1\u6709\u7b26\u5408\u8fc7\u6ee4\u6761\u4ef6\u7684\u9898\u3002_",
        "extras_intro": "\u540c\u8fc7\u6ee4\u6761\u4ef6\u4e0b\u7684\u5907\u9009 \u2014 \u6709\u65f6\u95f4\u518d\u505a\u3002",
        "mix_label": "\u9898\u578b\u914d\u6bd4",
        "filters_label": "\u8fc7\u6ee4\u6761\u4ef6",
    },
}


def load_index() -> list[dict]:
    if not INDEX.exists():
        sys.exit(
            f"Index not found at {INDEX}. Run `python tools/build_index.py` first."
        )
    try:
        return json.loads(INDEX.read_text(encoding="utf-8"))["questions"]
    except (KeyError, json.JSONDecodeError) as e:
        sys.exit(f"Failed to read {INDEX}: {e}")


def load_due_review_ids() -> list[str]:
    """Ids from the spaced-repetition store whose due date has arrived."""
    if not REVIEW_STATE.exists():
        return []
    try:
        reviews = json.loads(REVIEW_STATE.read_text(encoding="utf-8")).get("reviews", {})
    except json.JSONDecodeError:
        return []
    today = _dt.date.today().isoformat()
    due = [(qid, c.get("due", "9999-12-31")) for qid, c in reviews.items()]
    due = [qid for qid, d in due if d <= today]
    due.sort(key=lambda qid: reviews[qid].get("due", ""))
    return due


def classify_kind(q: dict) -> str:
    topics = {t.lower() for t in q.get("topics", [])}
    category = q.get("category", "")
    if category == "behavioral" or "behavioral" in topics:
        return "behavioral"
    if "system-design" in topics or "system design" in topics:
        return "system-design"
    if category == "knowledge" or "domain-knowledge" in topics:
        return "knowledge"
    if category in {"interviews", "knowledge", "behavioral", "mock-interviews"}:
        # Default to algorithm for interview-style coding questions
        return "algorithm"
    return "other"


def parse_mix(spec: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for piece in spec.split(","):
        piece = piece.strip()
        if not piece:
            continue
        if ":" not in piece:
            sys.exit(f"Bad --mix entry '{piece}'. Use kind:count syntax.")
        kind, count = piece.split(":", 1)
        try:
            out[kind.strip()] = int(count)
        except ValueError:
            sys.exit(f"Bad count in --mix entry '{piece}'.")
    return out


def filter_pool(
    pool: list[dict],
    *,
    company: str | None,
    category: str | None,
    topic: str | None,
    difficulty: str | None,
) -> list[dict]:
    out = pool
    if company:
        target = f"interviews/companies/{company.lower()}.md"
        out = [q for q in out if q["file"].lower() == target]
    if category:
        out = [q for q in out if q.get("category") == category]
    if topic:
        t = topic.lower()
        out = [q for q in out if any(t == x.lower() for x in q.get("topics", []))]
    if difficulty:
        d = difficulty.lower()
        out = [
            q
            for q in out
            if (q.get("difficulty") or "").lower() == d
        ]
    return out


def pick_mix(
    pool: list[dict],
    mix: dict[str, int],
    rng: random.Random,
) -> tuple[list[dict], list[str]]:
    """Pick questions per kind. Returns (picks, warnings)."""
    picks: list[dict] = []
    warnings: list[str] = []
    by_kind: dict[str, list[dict]] = {}
    for q in pool:
        by_kind.setdefault(classify_kind(q), []).append(q)
    for kind, want in mix.items():
        bucket = by_kind.get(kind, [])
        if not bucket:
            warnings.append(f"no '{kind}' questions matched the filters")
            continue
        take = min(want, len(bucket))
        picks.extend(rng.sample(bucket, take))
        if take < want:
            warnings.append(
                f"only {take}/{want} '{kind}' questions available after filtering"
            )
    return picks, warnings


def pick_extras(
    pool: list[dict],
    already: list[dict],
    n: int,
    rng: random.Random,
) -> list[dict]:
    used_ids = {q["id"] for q in already}
    candidates = [q for q in pool if q["id"] not in used_ids]
    if not candidates:
        return []
    return rng.sample(candidates, min(n, len(candidates)))


def render_question(q: dict, idx: int, lang: str, *, review: bool = False) -> str:
    t = TEMPLATES[lang]
    kind = classify_kind(q)
    budget = KIND_TIME_BUDGET_MIN.get(kind, KIND_TIME_BUDGET_MIN["other"])
    title = q["title_zh"] if lang == "zh" and q.get("title_zh") else q["title"]
    if review:
        title = f"🔁 {title}"
    file = q["file_zh"] if lang == "zh" and q.get("file_zh") else q["file"]
    line = q["line"]
    topics = ", ".join(q.get("topics", [])) or "-"
    difficulty = q.get("difficulty") or "-"

    lines = [
        t["q_heading"].format(idx=idx, title=title),
        "",
        t["q_meta"].format(
            kind=kind, difficulty=difficulty, budget=budget, file=file, line=line
        ),
        "",
        t["q_topics"].format(topics=topics),
        "",
        t["q_box"],
    ]
    extra_boxes = {
        "algorithm": t["q_box_algo"],
        "system-design": t["q_box_sd"],
        "behavioral": t["q_box_beh"],
    }.get(kind, [])
    lines.extend(extra_boxes)
    lines.extend(["", t["q_takeaway"], ""])
    return "\n".join(lines)


def render_plan(
    picks: list[dict],
    extras: list[dict],
    *,
    date: str,
    lang: str,
    mix: dict[str, int],
    filters_desc: str,
    warnings: list[str],
    review_ids: set[str] | None = None,
) -> str:
    t = TEMPLATES[lang]
    review_ids = review_ids or set()
    total = sum(
        KIND_TIME_BUDGET_MIN.get(classify_kind(q), KIND_TIME_BUDGET_MIN["other"])
        for q in picks
    )
    parts: list[str] = [
        t["title"].format(date=date),
        "",
        t["intro"].format(total_min=total),
        "",
        f"**{t['mix_label']}:** "
        + (", ".join(f"{k}\u00d7{v}" for k, v in mix.items()) or "-"),
        f"**{t['filters_label']}:** {filters_desc or '-'}",
        "",
    ]
    if warnings:
        parts.append("> " + " | ".join(warnings))
        parts.append("")
    parts.append(t["section_questions"])
    parts.append("")
    if not picks:
        parts.append(t["no_picks_msg"])
    else:
        for i, q in enumerate(picks, 1):
            parts.append(render_question(q, i, lang, review=q["id"] in review_ids))
    if extras:
        parts.append(t["section_extras"])
        parts.append("")
        parts.append(t["extras_intro"])
        parts.append("")
        for i, q in enumerate(extras, len(picks) + 1):
            parts.append(render_question(q, i, lang))
    parts.append(t["section_eval"])
    parts.append("")
    parts.extend(t["eval_items"])
    parts.append("")
    parts.append(t["section_notes"])
    parts.append("")
    parts.append("_..._")
    parts.append("")
    return "\n".join(parts)


def seed_from(args_seed: int | None, date_str: str) -> int:
    if args_seed is not None:
        return args_seed
    h = hashlib.sha1(date_str.encode("utf-8")).hexdigest()
    return int(h[:8], 16)


def describe_filters(
    company: str | None,
    category: str | None,
    topic: str | None,
    difficulty: str | None,
) -> str:
    bits = []
    if company:
        bits.append(f"company={company}")
    if category:
        bits.append(f"category={category}")
    if topic:
        bits.append(f"topic={topic}")
    if difficulty:
        bits.append(f"difficulty={difficulty}")
    return ", ".join(bits)


def main(argv: Iterable[str] | None = None) -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--company", help="Filter to a single company file (amazon, google, meta, ...)")
    p.add_argument("--category", help="Filter to a top-level category (interviews, knowledge, behavioral, mock-interviews)")
    p.add_argument("--topic", help="Filter by a single Topics tag (e.g. 'sliding-window')")
    p.add_argument("--difficulty", help="Exact match on Difficulty (e.g. 'Medium', 'L5')")
    p.add_argument(
        "--mix",
        default=DEFAULT_MIX,
        help=f"Counts per kind, comma-separated (default '{DEFAULT_MIX}'). Kinds: algorithm, system-design, behavioral, knowledge.",
    )
    p.add_argument("--count", type=int, help="Override total count (distributes evenly across mix kinds).")
    p.add_argument("--extras", type=int, default=2, help="Number of stretch picks appended (default 2).")
    p.add_argument("--review", type=int, default=0, help="Prepend up to N due spaced-repetition questions (see review.py).")
    p.add_argument("--date", help="Date string for the plan header and default seed (default today, YYYY-MM-DD).")
    p.add_argument("--seed", type=int, help="Random seed (default derived from --date).")
    p.add_argument("--lang", choices=("en", "zh"), default="en", help="Plan language (default en).")
    p.add_argument("--output", help="Write the plan to this file instead of stdout.")
    args = p.parse_args(argv)

    date_str = args.date or _dt.date.today().isoformat()
    rng = random.Random(seed_from(args.seed, date_str))

    pool = load_index()
    pool = filter_pool(
        pool,
        company=args.company,
        category=args.category,
        topic=args.topic,
        difficulty=args.difficulty,
    )

    mix = parse_mix(args.mix)
    if args.count is not None:
        total_default = sum(mix.values()) or 1
        scale = args.count / total_default
        mix = {k: max(1, round(v * scale)) for k, v in mix.items()}

    picks, warnings = pick_mix(pool, mix, rng)

    review_ids: set[str] = set()
    if args.review > 0:
        index_by_id = {q["id"]: q for q in load_index()}
        picked_ids = {q["id"] for q in picks}
        review_picks = []
        for qid in load_due_review_ids():
            if len(review_picks) >= args.review:
                break
            q = index_by_id.get(qid)
            if q and qid not in picked_ids:
                review_picks.append(q)
                review_ids.add(qid)
        if review_picks:
            picks = review_picks + picks
        elif not warnings:
            warnings.append("no spaced-repetition reviews due today")

    extras = pick_extras(pool, picks, args.extras, rng) if args.extras > 0 else []

    plan = render_plan(
        picks,
        extras,
        date=date_str,
        lang=args.lang,
        mix=mix,
        filters_desc=describe_filters(
            args.company, args.category, args.topic, args.difficulty
        ),
        warnings=warnings,
        review_ids=review_ids,
    )

    if args.output:
        out_path = Path(args.output).expanduser()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(plan, encoding="utf-8")
        print(f"Wrote {len(plan)} chars to {out_path}")
    else:
        try:
            sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
        except (AttributeError, OSError):
            pass
        sys.stdout.write(plan)


if __name__ == "__main__":
    main()
